### PR TITLE
Add support for JDK 8

### LINKED ISSUE #137: MAJOR: Update library to support JDK 8 along side JDK 11
This feature should expand the API to support JDK 8+ and android devices(?).

### PR DESCRIPTION
**Pull request by Katsute**
Closes #137 

- Adds support for JDK 8+.
- Preserves JDK 9+ modularity.
- Updates CI to test JRE 8+
- Adds timeout to HTTP requests

### CODE REVIEW

**Comment by Katsute** [comment]
TODO: fix matcher replace all method

**Comment by Katsute** [comment]
TODO: Fix http request

**Comment by Katsute** [comment]
TODO: add test fail messages for list status tests; indicate if fail is likely caused by a previous failed test

**Comment by Katsute** [comment]
TODO: API call test using local sun http server.

**Comment by Katsute** [comment]
Module 9-10 has issue, requires `--add-opens java.base/java.lang.reflect=Mal4J --add-opens java.base/java.net=Mal4J`. Missing requires?

**Comment by Katsute** [comment]
Missing requires is not the cause, issue can not be resolved in library.

**Comment by Katsute** [comment]
All tests passed. Branch is ready to merge ✔.

**Comment by CryoliteDev** [comment]
Sorry to bother you but still having issues using the new version 2.0.0

image

**Comment by Katsute** [comment]
Opened #154. In the future please open a new issue rather than commenting on a closed pull/issue.

**Pull request merged**
